Repository octokit/request-action, pull requests merged in 2020-05, with the labels that each got.

#16 Replace Greenkeeper with Dependabot
  .github/dependabot.yml
  README.md
Labels: maintenance

#20 Declare mediaType as an optional input
  action.yml
Labels: feature

#27 fix(README): pass YAML strings instead of JSON strings
  .github/workflows/test.yml
  README.md
Labels: documentation, feature
